# Set the project language
language: cpp

# Set test platforms
os:
  - osx
  - linux

# Disable use of container-based infrastructure for Linux, because we need to
# add a non-whitelisted PPA for a newer version of CMake
sudo: true

# Configuration
env:
  global:
    - BUILD_SHARED_LIBS=1
  matrix:
    - CMAKE_BUILD_TYPE=Debug
    - CMAKE_BUILD_TYPE=RelWithDebInfo
    - CMAKE_BUILD_TYPE=Release
    - CMAKE_BUILD_TYPE=MinSizeRel

# Run the build and the test
script:
  - if [[ "`uname`" == "Linux" ]]; then sudo add-apt-repository -y ppa:george-edison55/precise-backports && sudo apt-get update -qq; fi
  - if [[ "`uname`" == "Linux" ]]; then sudo sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y && sudo apt-get update -qq; fi
  - if [[ "`uname`" == "Linux" ]]; then sudo apt-get install cmake-data cmake; fi
  - if [[ "`uname`" == "Linux" ]]; then sudo apt-get install g++-4.8 gcc-4.8; fi
  - if [[ "`uname`" == "Linux" ]]; then export CXX=g++-4.8 && export CC=gcc-4.8; fi
  - ./clone.sh foo
  - cd foo
  - ./build.sh
  - ls -lhR _install/*
  - ./tests-install.sh

# Send notifications
notifications:
  email:
    - twiddlebits.ak@gmail.com
